O_TARGET := hw_nat.o

obj-y := ra_nat.o foe_fdb.o util.o acl_policy.o ac_policy.o mtr_policy.o
obj-y += ac_ioctl.o hwnat_ioctl.o acl_ioctl.o mtr_ioctl.o
obj-m := $(O_TARGET)
export-objs :=  ra_nat.o

include $(TOPDIR)/Rules.make
