/*
 * 
 * Copyright (c) Ralink Technology Corporation All Rights Reserved.
 *
 */

#ifndef	RALINK_ESW_MIB
#define	RALINK_ESW_MIB

CVoidType ralink_esw_init(void);

#define ESW_MAXTYPE	17
#define ESW_OID		"\53\6\1\4\1\1107\1\1\1\1"

#define	RALINKESW_CDMAFCCFG	0
#define	RALINKESW_GDMA1FCCFG	1
#define	RALINKESW_PDMAFCCFG	2
#define	RALINKESW_GDMA1SCHCFG	3
#define	RALINKESW_GDMA2SCHCFG	4
#define	RALINKESW_PDMASCHCFG	5
#define	RALINKESW_GDMAGBCNT0	6
#define	RALINKESW_GDMAGPCNT0	7
#define	RALINKESW_GDMAOERCNT0	8
#define	RALINKESW_GDMAFERCNT0	9
#define	RALINKESW_GDMASERCNT0	10
#define	RALINKESW_GDMALERCNT0	11
#define	RALINKESW_GDMACERCNT0	12

#define	RALINKESW_PORT0CNT	13
#define	RALINKESW_PORT1CNT	14
#define	RALINKESW_PORT2CNT	15
#define	RALINKESW_PORT3CNT	16
#define	RALINKESW_PORT4CNT	17
#define	RALINKESW_PORT5CNT	18
#endif
