#
# pppstats makefile
# $Id: Makefile.sunos4,v 1.1.1.1 2007-08-22 05:38:26 steven Exp $
#

include ../sunos4/Makedefs

OBJS = pppdump.o bsd-comp.o deflate.o zlib.o
CFLAGS = $(COPTS) -I../include/net

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f pppdump $(OBJS) *~

install: pppdump
	$(INSTALL) -c pppdump $(BINDIR)/pppdump
	$(INSTALL) -c -m 444 pppdump.8 $(MANDIR)/man8/pppdump.8
