.TH WD_KEEPALIVE 8 "January 2005"
.UC 4
.SH NAME
wd_keepalive \- a simplified software watchdog daemon
.SH SYNOPSIS
.B wd_keepalive
.RB [ \-c " \fIfilename\fR|" \-\-config\-file " \fIfilename\fR]"
.SH DESCRIPTION
This is a simplified version of the watchdog daemon. It only opens
.IR /dev/watchdog , 
and keeps writing to it often enough to keep the kernel from resetting,
at least once per minute. Each write delays the reboot
time another minute. After a minute of inactivity the watchdog hardware will
cause a reset. In the case of the software watchdog the ability to 
reboot will depend on the state of the machines and interrupts.
.PP
The wd_keepalive daemon can be stopped without causing a reboot if the device 
.I /dev/watchdog
is closed correctly, unless your kernel is compiled with the
.I CONFIG_WATCHDOG_NOWAYOUT
option enabled.
.SH OPTIONS
Available command line options are the following:
.TP
.BR \-c " \fIconfig-file\fR, " \-\-config\-file " \fIconfig-file"
Use
.I config-file
as the configuration file instead of the default 
.IR /etc/watchdog.conf .
.SH FILES
.TP
.I /dev/watchdog  
The watchdog device.
.TP
.I /var/run/wd_keepalive.pid 
The pid file of the running 
.BR wd_keepalive .
.SH "SEE ALSO"
.BR watchdog.conf (5)
.TP
.BR watchdog (8)
