# /**************************************
#  ecmh - Easy Cast du Multi Hub
#  by Jeroen Massar <jeroen@unfix.org>
# ***************************************
# $Author: chhung $
# $Id: Makefile,v 1.1 2011-03-15 14:23:23 chhung Exp $
# $Date: 2011-03-15 14:23:23 $
# **************************************/
#
# Tools Makefile
#

all:	mtrace6

mtrace6: mtrace6/
	$(MAKE) -C mtrace6 all

clean:
	$(MAKE) -C mtrace6 clean

# Mark targets as phony
.PHONY : all clean mtrace6

