/* include/autoconf.h.  Generated by configure.  */
/* auto maticaly */
#define STDC_HEADERS 1

#define HAVE_INTTYPES_H 1

#define HAVE_STDINT_H 1

#define TIME_WITH_SYS_TIME 1

/* #undef HAVE_SYS_TIME_H */


#define HAVE_MALLOC_H 1

#define HAVE_POLL_H 1

#define HAVE_SYS_EPOLL_H 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_DLFCN_H 1

#define HAVE_TERMCAP_H 1

/* #undef USE_NCURSES_DB */

/* #undef HAVE_SYS_FILIO_H */

#define HAVE_SYS_UIO_H 1

#define HAVE_SYS_UN_H 1

#define HAVE_ZLIB_H 1

#define HAVE_SYS_PRCTL_H 1


/* #undef const */


/* #undef mode_t */
/* #undef off_t */
/* #undef off64_t */
#define HAVE_OFF64_T 1
/* #undef pid_t */
/* #undef size_t */
/* #undef ssize_t */
/* #undef uid_t */
/* #undef gid_t */
/* #undef ptrdiff_t */
/* #undef intmax_t */
/* #undef uintmax_t */
/* #undef uintptr_t */
#define HAVE_LONG_LONG 1
/* #undef uint_least16_t */
/* #undef uint_least32_t */

/* auto macors... */
#define HAVE_UNISTD_H 1
#define HAVE_MMAP 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_STRFTIME 1
/* #undef HAVE_VFORK_H */
/* #undef vfork */


#define HAVE_MEMCHR 1

#define HAVE_MEMRCHR 1

#define HAVE_MEMCPY 1

#define HAVE_MEMPCPY 1

#define HAVE_MEMCMP 1

#define HAVE_MEMMEM 1

#define HAVE_STRSPN 1

#define HAVE_STRCSPN 1

#define HAVE_STPCPY 1

#define HAVE_STRNCMP 1

#define HAVE_STRCASECMP 1

#define HAVE_STRNCASECMP 1

#define HAVE_STRNLEN 1

#define HAVE_ASPRINTF 1

#define HAVE_STRERROR_R 1


#define HAVE_OPEN64 1

#define HAVE_MMAP64 1

#define HAVE_WCSNRTOMBS 1

#define USE_WIDE_CHAR_T 1

#define HAVE_GETOPT_LONG 1

#define HAVE_SIGEMPTYSET 1

#define HAVE_DIFFTIME 1

#define HAVE_SIGACTION 1

#define HAVE_STRERROR 1


#define HAVE_INET_NTOP 1

/* #undef HAVE_INET_NTOA */

#define HAVE_INET_PTON 1

/* #undef HAVE_INET_ATON */

/* #undef HAVE_INET_ADDR */

#define HAVE_PREAD 1

/* #undef open64 */
/* #undef mmap64 */
/* #undef lseek64 */
/* #undef fstat64 */
/* #undef stat64 */

#define ASM_GLOBAL_DIRECTIVE .globl

#define HAVE_OFFSETOF 1

#define HAVE_VA_COPY 1

#define HAVE___VA_COPY 1

#define HAVE_POLL 1

/* #undef HAVE_WRITEV */

#define HAVE_DL_RTLD_GLOBAL 1

#define HAVE_C9X_SNPRINTF_RET 1
#define HAVE_C9X_SPRINTF_FMT_F 1
#define HAVE_C9X_SPRINTF_FMT_A 1
#define HAVE_C9X_SPRINTF_FMT_a 1

#define HAVE_SETRLIMIT 1

#define HAVE_PRCTL 1

#define HAVE_SIGCONTEXT 1

/* #undef HAVE_OLD_SIGCONTEXT */

#define HAVE_MALLINFO 1

/* #undef HAVE_DECL_TERMCAP_VARS */

#define USE_QUICK_ADD_TIME 1

#define HAVE_SIGALTSTACK 1

#define HAVE_C9x_STRUCT_HACK 1

#define HAVE_CMSGHDR_STRUCT 1

#define HAVE_CMSGHDR_RIGHTS 1

#define HAVE_CMSGHDR_CREDENTIALS 1

#define HAVE_SO_PEERCREDS 1

#define HAVE_TCP_CORK 1

#define HAVE_CMSG_DATA 1

#define HAVE_SENDFILE 1

/* #undef HAVE_SENDFILE_FREEBSD */

#define HAVE_SOCKADDR_IN6 1

#define ULONG_MAX_LEN 10

#define NDEBUG 1

#define FMT_DBL_host 1
/* #undef FMT_DBL_glibc */
/* #undef FMT_DBL_none */

/* #undef HAVE_LINKER_SCRIPT */

#define HAVE_POSIX_HOST 1

#define HAVE_INLINE 1

#define HAVE_ATTRIB_ALIAS 1

#define HAVE_ATTRIB_DEPRECATED 1

#define HAVE_ATTRIB_MALLOC 1

#define HAVE_ATTRIB_NONNULL 1

#define HAVE_ATTRIB_PURE 1

#define HAVE_ATTRIB_CONST 1

#define HAVE_ATTRIB_VISIBILITY 1

#define HAVE_ATTRIB_WARN_UNUSED_RET 1

#define HAVE___TYPEOF 1

/* #undef USE_WRAP_MEMCPY */

/* #undef USE_WRAP_MEMCMP */

/* #undef USE_WRAP_MEMCHR */

/* #undef USE_WRAP_MEMRCHR */

/* #undef USE_WRAP_MEMSET */

/* #undef USE_WRAP_MEMMOVE */

#define USE_SYSCALL_ASM 1

#define USE_ASSERT_LOOP 1
